port: 2355
save_video: true
seed: 0

PipelineParams:
  convert_SHs_python: true #true = using direct rgb
ModelParams:
  workspace: "subjects/jackman"
  sh_degree: 0
  bg_aug_ratio: 0.66

GuidanceParams:
  model_key: 'runwayml/stable-diffusion-v1-5'
  text: 'A portrait of a person, head, photorealistic'
  negative: 'unrealistic, blurry, low quality, out of focus, ugly, low contrast, dull, dark, low-resolution, gloomy, oversaturation, purple shadows, weird colors'
  inverse_text: ''

  C_batch_size: 4

  t_range: [0.02, 0.5]
  max_t_range: 0.98
  lambda_guidance: 0.1
  guidance_scale: 1.25
  denoise_guidance_scale: 1.0
  noise_seed: 5252323

  ddim_inv: true
  annealing_intervals: true

  xs_delta_t: 50
  xs_inv_steps: 20
  xs_eta: 0.0

  delta_t: 50
  delta_t_start: 100

  lora_scale: 0.45

GenerateCamParams:
  phi_range: [-180, 180]
  max_phi_range: [-180, 180]
  rand_cam_gamma: 1.5

  theta_range: [55, 100]
  max_theta_range: [55, 100]

  radius_range: [5.6, 5.9]
  max_radius_range: [4.6, 5.9] 
  default_radius: 4.5

  default_fovy: 0.7
  fovy_range: [0.4, 0.6]  
  max_fovy_range: [0.3, 0.7]  

OptimizationParams:
  subject_id: "subjects/jackman"
  iterations: 7000
  save_process: True
  pro_frames_num: 600
  pro_render_45: False
  warmup_iter: 1

  lambda_tv: 1

  as_latent_ratio : 0
  geo_iter : 0
  densify_from_iter: 100
  densify_until_iter: 3000
  densification_interval: 200
  percent_dense: 0.5
  densify_grad_threshold: 0.005
  progressive_view_iter: 0
  opacity_reset_interval: 400

  scale_up_cameras_iter: 1500
  fovy_scale_up_factor: [0.8, 1.1]
  phi_scale_up_factor: 1.5
